# Created with package:mono_repo v2.3.0
language: dart

jobs:
  include:
    - stage: analyze
      name: "SDK: stable; PKG: petitparser; TASKS: `dartanalyzer --fatal-warnings .`"
      dart: stable
      os: linux
      env: PKGS="petitparser"
      script: ./tool/travis.sh command_0
    - stage: analyze
      name: "SDK: stable; PKG: petitparser; TASKS: `dartfmt --dry-run --set-exit-if-changed .`"
      dart: stable
      os: linux
      env: PKGS="petitparser"
      script: ./tool/travis.sh command_1
    - stage: analyze
      name: "SDK: stable; PKG: petitparser_examples; TASKS: `dartanalyzer --fatal-warnings .`"
      dart: stable
      os: linux
      env: PKGS="petitparser_examples"
      script: ./tool/travis.sh command_0
    - stage: analyze
      name: "SDK: stable; PKG: petitparser_examples; TASKS: `dartfmt --dry-run --set-exit-if-changed .`"
      dart: stable
      os: linux
      env: PKGS="petitparser_examples"
      script: ./tool/travis.sh command_1
    - stage: unit_test
      name: "SDK: stable; PKG: petitparser; TASKS: `pub run test test/all_test.dart --platform vm`"
      dart: stable
      os: linux
      env: PKGS="petitparser"
      script: ./tool/travis.sh command_2
    - stage: unit_test
      name: "SDK: stable; PKG: petitparser; TASKS: `pub run test test/all_test.dart --platform chrome`"
      dart: stable
      os: linux
      env: PKGS="petitparser"
      script: ./tool/travis.sh command_3
    - stage: unit_test
      name: "SDK: stable; PKG: petitparser_examples; TASKS: `pub run test --platform vm`"
      dart: stable
      os: linux
      env: PKGS="petitparser_examples"
      script: ./tool/travis.sh command_5
    - stage: unit_test
      name: "SDK: stable; PKG: petitparser_examples; TASKS: `pub run test --platform chrome`"
      dart: stable
      os: linux
      env: PKGS="petitparser_examples"
      script: ./tool/travis.sh command_6
    - stage: coverage
      name: "SDK: stable; PKG: petitparser; TASKS: `pub global activate dart_coveralls && dart_coveralls report test/all_test.dart`"
      dart: stable
      os: linux
      env: PKGS="petitparser"
      script: ./tool/travis.sh command_4

stages:
  - analyze
  - unit_test
  - coverage

# Only building master means that we don't run two builds for each pull request.
branches:
  only:
    - master

cache:
  directories:
    - "$HOME/.pub-cache"
    - petitparser/.dart_tool/build
    - petitparser_examples/.dart_tool/build
