# Created with package:mono_repo v2.3.0
language: dart

# Custom configuration
sudo: required

jobs:
  include:
    - stage: analyze
      name: "SDK: dev; PKG: example; TASKS: `dartanalyzer --fatal-warnings .`"
      dart: dev
      os: linux
      env: PKGS="example"
      script: ./tool/travis.sh command_0
    - stage: analyze
      name: "SDK: dev; PKG: example; TASKS: `dartfmt --dry-run --set-exit-if-changed .`"
      dart: dev
      os: linux
      env: PKGS="example"
      script: ./tool/travis.sh command_1
    - stage: analyze
      name: "SDK: dev; PKG: petitparser; TASKS: `dartanalyzer --fatal-warnings .`"
      dart: dev
      os: linux
      env: PKGS="petitparser"
      script: ./tool/travis.sh command_0
    - stage: analyze
      name: "SDK: dev; PKG: petitparser; TASKS: `dartfmt --dry-run --set-exit-if-changed .`"
      dart: dev
      os: linux
      env: PKGS="petitparser"
      script: ./tool/travis.sh command_1
    - stage: unit_test
      name: "SDK: dev; PKG: example; TASKS: `pub run test --platform vm`"
      dart: dev
      os: linux
      env: PKGS="example"
      script: ./tool/travis.sh command_2
    - stage: unit_test
      name: "SDK: dev; PKG: example; TASKS: `pub run test --platform chrome`"
      dart: dev
      os: linux
      env: PKGS="example"
      script: ./tool/travis.sh command_3
    - stage: unit_test
      name: "SDK: dev; PKG: petitparser; TASKS: `pub run test test/all_test.dart --platform vm`"
      dart: dev
      os: linux
      env: PKGS="petitparser"
      script: ./tool/travis.sh command_4
    - stage: unit_test
      name: "SDK: dev; PKG: petitparser; TASKS: `pub run test test/all_test.dart --platform chrome`"
      dart: dev
      os: linux
      env: PKGS="petitparser"
      script: ./tool/travis.sh command_5
    - stage: coverage
      name: "SDK: dev; PKG: petitparser; TASKS: `pub global activate dart_coveralls && dart_coveralls report test/all_test.dart`"
      dart: dev
      os: linux
      env: PKGS="petitparser"
      script: ./tool/travis.sh command_6

stages:
  - analyze
  - unit_test
  - coverage

# Only building master means that we don't run two builds for each pull request.
branches:
  only:
    - master

cache:
  directories:
    - "$HOME/.pub-cache"
    - "example/$HOME/.pub-cache"
    - example/.dart_tool/build
    - "petitparser/$HOME/.pub-cache"
    - petitparser/.dart_tool/build
