# Created with https://github.com/dart-lang/mono_repo
language: dart

jobs:
  include:
    - stage: analyze
      name: "SDK: dev - DIR: example - TASKS: dartanalyzer --fatal-warnings ."
      script: ./tool/travis.sh command_0
      env: PKG="example"
      dart: dev
    - stage: analyze
      name: "SDK: dev - DIR: example - TASKS: dartfmt --dry-run --set-exit-if-changed ."
      script: ./tool/travis.sh command_1
      env: PKG="example"
      dart: dev
    - stage: unit_test
      name: "SDK: dev - DIR: example - TASKS: pub run test --platform vm"
      script: ./tool/travis.sh command_2
      env: PKG="example"
      dart: dev
    - stage: unit_test
      name: "SDK: dev - DIR: example - TASKS: pub run test --platform chrome"
      script: ./tool/travis.sh command_3
      env: PKG="example"
      dart: dev
    - stage: analyze
      name: "SDK: dev - DIR: petitparser - TASKS: dartanalyzer --fatal-warnings ."
      script: ./tool/travis.sh command_0
      env: PKG="petitparser"
      dart: dev
    - stage: analyze
      name: "SDK: dev - DIR: petitparser - TASKS: dartfmt --dry-run --set-exit-if-changed ."
      script: ./tool/travis.sh command_1
      env: PKG="petitparser"
      dart: dev
    - stage: unit_test
      name: "SDK: dev - DIR: petitparser - TASKS: pub run test --platform vm"
      script: ./tool/travis.sh command_2
      env: PKG="petitparser"
      dart: dev
    - stage: unit_test
      name: "SDK: dev - DIR: petitparser - TASKS: pub run test --platform chrome"
      script: ./tool/travis.sh command_3
      env: PKG="petitparser"
      dart: dev

stages:
  - analyze
  - unit_test

# Only building master means that we don't run two builds for each pull request.
branches:
  only:
    - master

cache:
  directories:
    - "$HOME/.pub-cache"
    - "example/$HOME/.pub-cache"
    - example/.dart_tool/build
    - "petitparser/$HOME/.pub-cache"
    - petitparser/.dart_tool/build
