# Created with package:mono_repo v1.2.1
language: dart

# Custom configuration
sudo: required

jobs:
  include:
    - stage: analyze
      name: "SDK: dev - DIR: example - TASKS: dartanalyzer --fatal-warnings ."
      script: ./tool/travis.sh command_0
      env: PKG="example"
      dart: dev
    - stage: analyze
      name: "SDK: dev - DIR: example - TASKS: dartfmt --dry-run --set-exit-if-changed ."
      script: ./tool/travis.sh command_1
      env: PKG="example"
      dart: dev
    - stage: unit_test
      name: "SDK: dev - DIR: example - TASKS: pub run test --platform vm"
      script: ./tool/travis.sh command_2
      env: PKG="example"
      dart: dev
    - stage: unit_test
      name: "SDK: dev - DIR: example - TASKS: pub run test --platform chrome"
      script: ./tool/travis.sh command_3
      env: PKG="example"
      dart: dev
    - stage: analyze
      name: "SDK: dev - DIR: petitparser - TASKS: dartanalyzer --fatal-warnings ."
      script: ./tool/travis.sh command_0
      env: PKG="petitparser"
      dart: dev
    - stage: analyze
      name: "SDK: dev - DIR: petitparser - TASKS: dartfmt --dry-run --set-exit-if-changed ."
      script: ./tool/travis.sh command_1
      env: PKG="petitparser"
      dart: dev
    - stage: unit_test
      name: "SDK: dev - DIR: petitparser - TASKS: pub run test test/all_test.dart --platform vm"
      script: ./tool/travis.sh command_4
      env: PKG="petitparser"
      dart: dev
    - stage: unit_test
      name: "SDK: dev - DIR: petitparser - TASKS: pub run test test/all_test.dart --platform chrome"
      script: ./tool/travis.sh command_5
      env: PKG="petitparser"
      dart: dev
    - stage: coverage
      name: "SDK: dev - DIR: petitparser - TASKS: pub global activate dart_coveralls && dart_coveralls report test/all_test.dart"
      script: ./tool/travis.sh command_6
      env: PKG="petitparser"
      dart: dev

stages:
  - analyze
  - unit_test
  - coverage

# Only building master means that we don't run two builds for each pull request.
branches:
  only:
    - master

cache:
  directories:
    - "$HOME/.pub-cache"
    - "example/$HOME/.pub-cache"
    - example/.dart_tool/build
    - "petitparser/$HOME/.pub-cache"
    - petitparser/.dart_tool/build
